### 1 Dimension array

In [1]:
# First import the NumPy library
import numpy as np

In [2]:
a1 = np.array([20,40,50,100,130])    # this is called one dimension array 

# we can access the value through indexing 
print(a1[2])


50


In [3]:
# we can checked the different properties of an array.
a1.dtype, a1.ndim, a1.shape, a1.size, type(a1)



(dtype('int64'), 1, (5,), 5, numpy.ndarray)

#### Slicing

In [4]:
a1 = np.array([20,40,50,100,130]) 
a = a1[0:3]
print(a)

[20 40 50]


In [5]:
# we can also change elements by this method
a1[2] = 22
a1


array([ 20,  40,  22, 100, 130])

In [6]:
# simple statistical method 
mean = a1.mean()
print("mean", mean)

standard_deviation= a1.std()
print("standard deviation", standard_deviation)

# we can also find the min and max value using min() and max().
max_value = a1.max()
min_value = a1.min()
print("max", max_value)
print("min", min_value)

mean 62.4
standard deviation 44.53133728061622
max 130
min 20


Addition and Subtraction

In [7]:
#  addition of an array 
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
add_arr = np.add(arr1, arr2)
print(add_arr)

[30 32 34 36 38 40]


In [8]:
# Subtraction of an array
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
sub_arr = np.subtract(arr1, arr2)
print(sub_arr)

[-10 -10 -10 -10 -10 -10]


Multiplication and Division

In [9]:
# we will do the multiplication on the same array 
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
multip_arr = np.multiply(arr1, arr2)
print(multip_arr)
 
 # division 
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
div_arr = np.divide(arr1, arr2)
print(div_arr)

[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


#### Dot Product
dot product is different from the above traditional multiplication, in this the value are first multiplied and then added to give us value.

In [10]:
x = np.array([3, 5])
y = np.array([2, 4])
z = np.dot(x, y)
print(z)



26
